"""init_tables

Revision ID: 7ae0ebfaa066
Revises:
Create Date: 2026-05-27 22:13:05.785277

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

import lib.attachments.types

# revision identifiers, used by Alembic.
revision: str = "7ae0ebfaa066"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_oauth_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_sub", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_oauth_accounts_id"), "auth_oauth_accounts", ["id"], unique=False)
    op.create_index(op.f("ix_auth_oauth_accounts_provider"), "auth_oauth_accounts", ["provider"], unique=False)
    op.create_index(op.f("ix_auth_oauth_accounts_provider_sub"), "auth_oauth_accounts", ["provider_sub"], unique=False)
    op.create_index(op.f("ix_auth_oauth_accounts_user_id"), "auth_oauth_accounts", ["user_id"], unique=False)
    op.create_table(
        "auth_one_time_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("payload", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("requested_from", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_one_time_tokens_created_at"), "auth_one_time_tokens", ["created_at"], unique=False)
    op.create_index(op.f("ix_auth_one_time_tokens_expires_at"), "auth_one_time_tokens", ["expires_at"], unique=False)
    op.create_index(op.f("ix_auth_one_time_tokens_kind"), "auth_one_time_tokens", ["kind"], unique=False)
    op.create_index(op.f("ix_auth_one_time_tokens_token_hash"), "auth_one_time_tokens", ["token_hash"], unique=True)
    op.create_index(op.f("ix_auth_one_time_tokens_user_id"), "auth_one_time_tokens", ["user_id"], unique=False)
    op.create_table(
        "auth_refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("family_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("issued_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("rotated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_refresh_tokens_expires_at"), "auth_refresh_tokens", ["expires_at"], unique=False)
    op.create_index(op.f("ix_auth_refresh_tokens_family_id"), "auth_refresh_tokens", ["family_id"], unique=False)
    op.create_index(op.f("ix_auth_refresh_tokens_issued_at"), "auth_refresh_tokens", ["issued_at"], unique=False)
    op.create_index(op.f("ix_auth_refresh_tokens_revoked_at"), "auth_refresh_tokens", ["revoked_at"], unique=False)
    op.create_index(op.f("ix_auth_refresh_tokens_rotated_at"), "auth_refresh_tokens", ["rotated_at"], unique=False)
    op.create_index(op.f("ix_auth_refresh_tokens_status"), "auth_refresh_tokens", ["status"], unique=False)
    op.create_index(op.f("ix_auth_refresh_tokens_token_id"), "auth_refresh_tokens", ["token_id"], unique=True)
    op.create_index(op.f("ix_auth_refresh_tokens_user_id"), "auth_refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_sessions_created_at"), "auth_sessions", ["created_at"], unique=False)
    op.create_index(op.f("ix_auth_sessions_expires_at"), "auth_sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_auth_sessions_id"), "auth_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_auth_sessions_revoked_at"), "auth_sessions", ["revoked_at"], unique=False)
    op.create_index(op.f("ix_auth_sessions_session_id"), "auth_sessions", ["session_id"], unique=True)
    op.create_index(op.f("ix_auth_sessions_status"), "auth_sessions", ["status"], unique=False)
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "feeds",
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("site_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sa.TEXT(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("favicon_url", sa.TEXT(), nullable=True),
        sa.Column("is_spark", sa.Boolean(), nullable=False),
        sa.Column("format", sa.TEXT(), nullable=False),
        sa.Column("status", sa.TEXT(), nullable=False),
        sa.Column("etag", sa.VARCHAR(length=255), nullable=True),
        sa.Column("last_modified", sa.VARCHAR(length=255), nullable=True),
        sa.Column("last_fetched_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_error", sa.TEXT(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_feeds_description_trgm",
        "feeds",
        ["description"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
        postgresql_where=sa.text("description IS NOT NULL"),
    )
    op.create_index(op.f("ix_feeds_id"), "feeds", ["id"], unique=False)
    op.create_index(op.f("ix_feeds_is_spark"), "feeds", ["is_spark"], unique=False)
    op.create_index("ix_feeds_status", "feeds", ["status"], unique=False)
    op.create_index(
        "ix_feeds_title_trgm",
        "feeds",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
        postgresql_where=sa.text("title IS NOT NULL"),
    )
    op.create_index(op.f("ix_feeds_url"), "feeds", ["url"], unique=True)
    op.create_index(
        "ix_feeds_url_trgm",
        "feeds",
        ["url"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"url": "gin_trgm_ops"},
        postgresql_where=sa.text("url IS NOT NULL"),
    )
    op.create_table(
        "job_queues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_class", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("queue_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("kwargs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("recurring", sa.Boolean(), nullable=False),
        sa.Column("schedule_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("enqueued_at", sa.DateTime(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_queues_job_class"), "job_queues", ["job_class"], unique=False)
    op.create_index(op.f("ix_job_queues_job_id"), "job_queues", ["job_id"], unique=False)
    op.create_index(op.f("ix_job_queues_queue_name"), "job_queues", ["queue_name"], unique=False)
    op.create_index(op.f("ix_job_queues_recurring"), "job_queues", ["recurring"], unique=False)
    op.create_index(op.f("ix_job_queues_status"), "job_queues", ["status"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recipient_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notification_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("read_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("archived_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_notification_type"), "notifications", ["notification_type"], unique=False)
    op.create_index(op.f("ix_notifications_read_at"), "notifications", ["read_at"], unique=False)
    op.create_index(op.f("ix_notifications_recipient_id"), "notifications", ["recipient_id"], unique=False)
    op.create_index(op.f("ix_notifications_recipient_type"), "notifications", ["recipient_type"], unique=False)
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("p256dh", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("auth", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_push_subscriptions_endpoint"), "push_subscriptions", ["endpoint"], unique=True)
    op.create_index(op.f("ix_push_subscriptions_id"), "push_subscriptions", ["id"], unique=False)
    op.create_index(op.f("ix_push_subscriptions_user_id"), "push_subscriptions", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("password_salt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("roles", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_login_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("is_suspended", sa.Boolean(), nullable=False),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
        sa.Column("avatar", lib.attachments.types.AttachedImageField(), nullable=True),
        sa.Column("fever_key", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_users_email_trgm",
        "users",
        ["email"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"email": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_fever_key"), "users", ["fever_key"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_is_suspended"), "users", ["is_suspended"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_index(
        "ix_users_name_trgm",
        "users",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index("ix_users_search_vector", "users", ["search_vector"], unique=False, postgresql_using="gin")
    op.create_index(op.f("ix_users_uuid"), "users", ["uuid"], unique=True)
    op.create_table(
        "articles",
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("feed_id", sa.Uuid(), nullable=False),
        sa.Column("guid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sa.TEXT(), nullable=True),
        sa.Column("summary", sa.TEXT(), nullable=True),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("url", sa.TEXT(), nullable=True),
        sa.Column("author", sa.TEXT(), nullable=True),
        sa.Column("image_url", sa.TEXT(), nullable=True),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column("content_hash", sa.VARCHAR(length=64), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feeds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feed_id", "guid", name="uq_article_feed_guid"),
    )
    op.create_index(op.f("ix_articles_feed_id"), "articles", ["feed_id"], unique=False)
    op.create_index("ix_articles_feed_published", "articles", ["feed_id", "published_at"], unique=False)
    op.create_index(op.f("ix_articles_guid"), "articles", ["guid"], unique=False)
    op.create_index(op.f("ix_articles_id"), "articles", ["id"], unique=False)
    op.create_index(op.f("ix_articles_published_at"), "articles", ["published_at"], unique=False)
    op.create_index(op.f("ix_articles_slug"), "articles", ["slug"], unique=True)
    op.create_index(
        "ix_articles_title_trgm",
        "articles",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
        postgresql_where=sa.text("title IS NOT NULL"),
    )
    op.create_table(
        "folders",
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=500), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["folders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", "parent_id", name="uq_folder_user_name_parent"),
    )
    op.create_index(op.f("ix_folders_id"), "folders", ["id"], unique=False)
    op.create_index(
        "ix_folders_name_trgm",
        "folders",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_folders_parent_id"), "folders", ["parent_id"], unique=False)
    op.create_index(op.f("ix_folders_slug"), "folders", ["slug"], unique=True)
    op.create_index(op.f("ix_folders_user_id"), "folders", ["user_id"], unique=False)
    op.create_index(
        "uq_folders_root_name",
        "folders",
        ["user_id", "name"],
        unique=True,
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.create_table(
        "article_annotations",
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.TEXT(), nullable=False),
        sa.Column("body", sa.TEXT(), nullable=True),
        sa.Column("highlight_text", sa.TEXT(), nullable=True),
        sa.Column("highlight_start", sa.Integer(), nullable=True),
        sa.Column("highlight_end", sa.Integer(), nullable=True),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_article_annotations_id"), "article_annotations", ["id"], unique=False)
    op.create_table(
        "article_statuses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_starred", sa.Boolean(), nullable=False),
        sa.Column("is_bookmarked", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("bookmarked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "user_id", name="uq_article_status_article_user"),
    )
    op.create_index(op.f("ix_article_statuses_article_id"), "article_statuses", ["article_id"], unique=False)
    op.create_index(op.f("ix_article_statuses_id"), "article_statuses", ["id"], unique=False)
    op.create_index(op.f("ix_article_statuses_user_id"), "article_statuses", ["user_id"], unique=False)
    op.create_table(
        "feed_subscriptions",
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=500), nullable=True),
        sa.Column("feed_id", sa.Uuid(), nullable=False),
        sa.Column("folder_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["feed_id"], ["feeds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["folder_id"], ["folders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feed_id", "user_id", name="uq_feed_subscription_feed_user"),
    )
    op.create_index(op.f("ix_feed_subscriptions_feed_id"), "feed_subscriptions", ["feed_id"], unique=False)
    op.create_index(op.f("ix_feed_subscriptions_folder_id"), "feed_subscriptions", ["folder_id"], unique=False)
    op.create_index(op.f("ix_feed_subscriptions_id"), "feed_subscriptions", ["id"], unique=False)
    op.create_index(op.f("ix_feed_subscriptions_user_id"), "feed_subscriptions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feed_subscriptions_user_id"), table_name="feed_subscriptions")
    op.drop_index(op.f("ix_feed_subscriptions_id"), table_name="feed_subscriptions")
    op.drop_index(op.f("ix_feed_subscriptions_folder_id"), table_name="feed_subscriptions")
    op.drop_index(op.f("ix_feed_subscriptions_feed_id"), table_name="feed_subscriptions")
    op.drop_table("feed_subscriptions")
    op.drop_index(op.f("ix_article_statuses_user_id"), table_name="article_statuses")
    op.drop_index(op.f("ix_article_statuses_id"), table_name="article_statuses")
    op.drop_index(op.f("ix_article_statuses_article_id"), table_name="article_statuses")
    op.drop_table("article_statuses")
    op.drop_index(op.f("ix_article_annotations_id"), table_name="article_annotations")
    op.drop_table("article_annotations")
    op.drop_index("uq_folders_root_name", table_name="folders", postgresql_where=sa.text("parent_id IS NULL"))
    op.drop_index(op.f("ix_folders_user_id"), table_name="folders")
    op.drop_index(op.f("ix_folders_slug"), table_name="folders")
    op.drop_index(op.f("ix_folders_parent_id"), table_name="folders")
    op.drop_index(
        "ix_folders_name_trgm", table_name="folders", postgresql_using="gin", postgresql_ops={"name": "gin_trgm_ops"}
    )
    op.drop_index(op.f("ix_folders_id"), table_name="folders")
    op.drop_table("folders")
    op.drop_index(
        "ix_articles_title_trgm",
        table_name="articles",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
        postgresql_where=sa.text("title IS NOT NULL"),
    )
    op.drop_index(op.f("ix_articles_slug"), table_name="articles")
    op.drop_index(op.f("ix_articles_published_at"), table_name="articles")
    op.drop_index(op.f("ix_articles_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_guid"), table_name="articles")
    op.drop_index("ix_articles_feed_published", table_name="articles")
    op.drop_index(op.f("ix_articles_feed_id"), table_name="articles")
    op.drop_table("articles")
    op.drop_index(op.f("ix_users_uuid"), table_name="users")
    op.drop_index("ix_users_search_vector", table_name="users", postgresql_using="gin")
    op.drop_index(
        "ix_users_name_trgm", table_name="users", postgresql_using="gin", postgresql_ops={"name": "gin_trgm_ops"}
    )
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_is_suspended"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_fever_key"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(
        "idx_users_email_trgm", table_name="users", postgresql_using="gin", postgresql_ops={"email": "gin_trgm_ops"}
    )
    op.drop_table("users")
    op.drop_index(op.f("ix_push_subscriptions_user_id"), table_name="push_subscriptions")
    op.drop_index(op.f("ix_push_subscriptions_id"), table_name="push_subscriptions")
    op.drop_index(op.f("ix_push_subscriptions_endpoint"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    op.drop_index(op.f("ix_notifications_recipient_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_recipient_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_read_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_notification_type"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_job_queues_status"), table_name="job_queues")
    op.drop_index(op.f("ix_job_queues_recurring"), table_name="job_queues")
    op.drop_index(op.f("ix_job_queues_queue_name"), table_name="job_queues")
    op.drop_index(op.f("ix_job_queues_job_id"), table_name="job_queues")
    op.drop_index(op.f("ix_job_queues_job_class"), table_name="job_queues")
    op.drop_table("job_queues")
    op.drop_index(
        "ix_feeds_url_trgm",
        table_name="feeds",
        postgresql_using="gin",
        postgresql_ops={"url": "gin_trgm_ops"},
        postgresql_where=sa.text("url IS NOT NULL"),
    )
    op.drop_index(op.f("ix_feeds_url"), table_name="feeds")
    op.drop_index(
        "ix_feeds_title_trgm",
        table_name="feeds",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
        postgresql_where=sa.text("title IS NOT NULL"),
    )
    op.drop_index("ix_feeds_status", table_name="feeds")
    op.drop_index(op.f("ix_feeds_is_spark"), table_name="feeds")
    op.drop_index(op.f("ix_feeds_id"), table_name="feeds")
    op.drop_index(
        "ix_feeds_description_trgm",
        table_name="feeds",
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
        postgresql_where=sa.text("description IS NOT NULL"),
    )
    op.drop_table("feeds")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_status"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_session_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_revoked_at"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_created_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_auth_refresh_tokens_user_id"), table_name="auth_refresh_tokens")
    op.drop_index(op.f("ix_auth_refresh_tokens_token_id"), table_name="auth_refresh_tokens")
    op.drop_index(op.f("ix_auth_refresh_tokens_status"), table_name="auth_refresh_tokens")
    op.drop_index(op.f("ix_auth_refresh_tokens_rotated_at"), table_name="auth_refresh_tokens")
    op.drop_index(op.f("ix_auth_refresh_tokens_revoked_at"), table_name="auth_refresh_tokens")
    op.drop_index(op.f("ix_auth_refresh_tokens_issued_at"), table_name="auth_refresh_tokens")
    op.drop_index(op.f("ix_auth_refresh_tokens_family_id"), table_name="auth_refresh_tokens")
    op.drop_index(op.f("ix_auth_refresh_tokens_expires_at"), table_name="auth_refresh_tokens")
    op.drop_table("auth_refresh_tokens")
    op.drop_index(op.f("ix_auth_one_time_tokens_user_id"), table_name="auth_one_time_tokens")
    op.drop_index(op.f("ix_auth_one_time_tokens_token_hash"), table_name="auth_one_time_tokens")
    op.drop_index(op.f("ix_auth_one_time_tokens_kind"), table_name="auth_one_time_tokens")
    op.drop_index(op.f("ix_auth_one_time_tokens_expires_at"), table_name="auth_one_time_tokens")
    op.drop_index(op.f("ix_auth_one_time_tokens_created_at"), table_name="auth_one_time_tokens")
    op.drop_table("auth_one_time_tokens")
    op.drop_index(op.f("ix_auth_oauth_accounts_user_id"), table_name="auth_oauth_accounts")
    op.drop_index(op.f("ix_auth_oauth_accounts_provider_sub"), table_name="auth_oauth_accounts")
    op.drop_index(op.f("ix_auth_oauth_accounts_provider"), table_name="auth_oauth_accounts")
    op.drop_index(op.f("ix_auth_oauth_accounts_id"), table_name="auth_oauth_accounts")
    op.drop_table("auth_oauth_accounts")
    # ### end Alembic commands ###
