{
 "title": "Feedbase",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{method}} {{handler}}" }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) / sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(request_errors_total)" }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{status=~\"2.*\"}) / sum by(handler) (http_requests_total)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{status=~\"5.*\"}) / sum by(handler) (http_requests_total)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    { "expr": "requests_in_progress", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{handler}}" }
   ]
  },
  {
   "title": "Job Processed Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(name, status) (rate(jobs_processed_total[5m]))",
     "legendFormat": "{{name}} {{status}}"
    }
   ]
  },
  {
   "title": "Job Duration 99th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jobs_duration_seconds_bucket[1m])) by (name, status, le))",
     "legendFormat": "{{name}} {{status}}"
    }
   ]
  },
  {
   "title": "Template Render 99th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(template_render_seconds_bucket[1m])) by (name, le))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(level) (rate({compose_service=\"feedbase_app\"} | json | level != \"\" |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Feedbase Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "{compose_service=\"feedbase_app\"} | json | line_format \"{{.compose_service}}\\t{{.level}}\\t request_id={{.request_id}}\\t path={{.path}}\\t {{.msg}}\" |= \"$log_keyword\""
    }
   ]
  }
 ]
}