import uuid
from datetime import datetime
from typing import Any

from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
from pydantic import EmailStr
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import TIMESTAMP, Column, Field

from lib.database.mixins import BaseMixin, SoftDeletableMixin, TimestampMixin

_REQUIRED_FIELDS = frozenset(
    {
        "id",
        "email",
        "hashed_password",
        "password_salt",
        "email_verified",
        "is_active",
        "created_at",
        "updated_at",
    }
)


def generate_salt() -> str:
    """
    Generate a 32-byte cryptographically random hex salt.
    """
    return ChaCha20Poly1305.generate_key().hex()


class AuthUserMixin:
    """
    Abstract mixin every auth user model must implement.
    """

    id: Any
    email: str | EmailStr
    hashed_password: str | None
    password_salt: str
    email_verified: bool
    is_active: bool
    created_at: datetime
    updated_at: datetime | None
    roles: list
    permissions: list

    def get_id(self) -> str:
        """
        Return the user's PK as a string for the JWT 'sub' claim.
        """
        return str(self.id)

    def get_display_name(self) -> str:
        """
        Human-readable label for logs and UI. Override as needed.
        """
        name = getattr(self, "name", None)

        if name and len(name) == 0:
            return self.email
        elif name is None:
            return self.email

        return name

    @staticmethod
    def generate_password_salt() -> str:
        """
        Generate a new random password salt.

        Called automatically by SQLModelAuthUser.  For raw SQLAlchemy models,
        call this in your column default:

            password_salt: Mapped[str] = mapped_column(default=AuthUserMixin.generate_password_salt)
        """
        return generate_salt()

    def has_role(self, role: str) -> bool:
        return role in (getattr(self, "roles", None) or [])

    def has_any_role(self, *roles: str) -> bool:
        return any(self.has_role(r) for r in roles)

    def has_all_roles(self, *roles: str) -> bool:
        return all(self.has_role(r) for r in roles)

    def has_permission(self, permission: str) -> bool:
        return permission in (getattr(self, "permissions", None) or [])

    def has_any_permission(self, *permissions: str) -> bool:
        return any(self.has_permission(p) for p in permissions)

    def has_all_permissions(self, *permissions: str) -> bool:
        return all(self.has_permission(p) for p in permissions)

    def is_superuser(self) -> bool:
        return self.has_role("superuser")

    def is_superadmin(self) -> bool:
        return self.has_role("superadmin")

    def is_admin(self) -> bool:
        return self.has_role("admin")

    @classmethod
    def __auth_validate__(cls) -> None:
        """
        Called by configure_auth() to verify required columns exist.
        Raises TypeError with a clear message on failure.
        """
        all_annotations: dict[str, Any] = {}

        for klass in reversed(cls.__mro__):
            all_annotations.update(getattr(klass, "__annotations__", {}))

        missing = _REQUIRED_FIELDS - set(all_annotations.keys())
        if missing:
            raise TypeError(
                f"{cls.__name__} is missing required AuthUserMixin field(s): "
                f"{sorted(missing)}.\n"
                f"Either subclass SQLModelAuthUser or declare these columns manually."
            )
        if not issubclass(cls, AuthUserMixin):
            raise TypeError(f"{cls.__name__} must subclass AuthUserMixin.")


class SQLModelAuthUser(AuthUserMixin, BaseMixin, SoftDeletableMixin, TimestampMixin):
    """
    SQLModel base that provides all required auth columns.

    Subclass with table=True and add your own application fields

    The table name is generated by :class:`BaseMixin` as the pluralized snake_case of your class name.

    Examples:

    ```python
        class User(SQLModelAuthUser, table=True):
            # This table will have the name "users" by default

            name:       str           = Field(default="")
            avatar_url: str | None    = Field(default=None)
    ```


    Attributes:

      id (int):
        Auto-incrementing integer primary key.
      uuid (str):
        Unique UUIDv7 string for stable JWT subject and public references.
      email (EmailStr):
        The user's email address, unique and indexed.
      email_verified (bool):
        Whether the user's email has been verified.
      hashed_password (str | None):
        The securely hashed password, or None if no password is set.
      password_salt (str):
        Unique salt for password hashing, auto-generated at creation.
      roles (list):
        List of role names assigned to the user, stored as JSONB.
      permissions (list):
        List of permission names assigned to the user, stored as JSONB.
      is_active (bool):
        Whether the user's account is active.
      created_at (datetime):
        Timestamp of when the user was created, auto-set at creation.
      updated_at (datetime | None):
        Timestamp of the last update to the user, auto-updated on change.
    """

    id: int = Field(primary_key=True, index=True)

    uuid: str = Field(
        default_factory=lambda: str(uuid.uuid7()),
        index=True,
        unique=True,
    )

    email: EmailStr = Field(unique=True, index=True)
    email_verified: bool = Field(default=False)
    hashed_password: str | None = Field(default=None)

    # Auto-generated once at creation, never regenerated.
    password_salt: str = Field(
        default_factory=generate_salt,
        nullable=False,
    )

    roles: list[str] = Field(sa_column=Column(JSONB(), default=list))
    permissions: list[str] = Field(sa_column=Column(JSONB(), default=list))

    is_active: bool = Field(default=True, index=True)

    last_login_at: datetime | None = Field(
        sa_column=Column(
            TIMESTAMP(timezone=True),
            default=None,
            nullable=True,
        )
    )

    def get_id(self) -> str:
        """
        Return uuid (not integer PK) as the stable JWT subject
        """
        return self.uuid

    @property
    def is_deleted(self) -> bool:
        """
        Check if the user is to be deleted.
        """
        return self.deleted_at is not None and not self.is_active
