from typing import TYPE_CHECKING, Any

from sqlalchemy import Index
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Column, Field, Relationship

from lib.attachments import AttachedImageField, SizeValidator, ThumbnailGenerator, blob_field
from lib.auth import SQLModelAuthUser
from lib.database.mixins import SearchableMixin

if TYPE_CHECKING:
    from models.article_status import ArticleStatus
    from models.feed_subscription import FeedSubscription
    from models.folder import Folder


class User(SQLModelAuthUser, SearchableMixin, table=True):
    """
    Represents a user in the system.

    Inherits from :class:`SQLModelAuthUser`, which provides the necessary fields and methods for authentication.


    Attributes:
        id (int): The unique identifier for the user, automatically generated by the database.
        uuid (UUID): A UUIDv7 identifier for the user, generated using the UUID7Mixin.
        email (EmailStr): The unique email address of the user, used for authentication.
        email_verified (bool): Whether the user's email address has been verified.
        is_active (bool): Whether the user's account is active. Inactive users cannot authenticate.
        hashed_password (str): The hashed password of the user, used for authentication.
        password_salt (str): The salt used for hashing the user's password.
        last_login_at (datetime | None): The datetime when the user last logged in.
        roles (list[str]): A list of roles assigned to the user, used for authorization.
        permissions (list[str]): A list of permissions assigned to the user, used for authorization.
        name (str): The display name of the user.
        is_suspended (bool): Whether the user's account is suspended.
        bio (str | None): A short biography of the user.
        avatar (AttachedImageField | None): The user's avatar image, stored as a blob in the database.
        preferences (dict[str, Any]): A JSONB field to store user preferences as a dictionary.
    """

    __table_args__ = (
        Index(
            "ix_users_search_vector",
            "search_vector",
            postgresql_using="gin",
        ),
        Index(
            "ix_users_name_trgm",
            "name",
            postgresql_using="gin",
            postgresql_ops={"name": "gin_trgm_ops"},
        ),
        Index(
            "idx_users_email_trgm",
            "email",
            postgresql_using="gin",
            postgresql_ops={"email": "gin_trgm_ops"},
        ),
    )

    model_config = {
        "arbitrary_types_allowed": True,
    }

    name: str = Field(..., max_length=1000, index=True)

    is_suspended: bool = Field(default=False, index=True)

    bio: str | None = Field(
        default=None,
        max_length=5000,
    )

    avatar: AttachedImageField | None = blob_field(
        nullable=True,
        image=True,
        validators=[SizeValidator(max_size="20M")],
        processors=[ThumbnailGenerator()],
    )

    fever_key: str | None = Field(
        default=None,
        max_length=32,
        unique=True,
        index=True,
        description="Fever Complaint API key regenerated on password change",
    )

    preferences: dict[str, Any] = Field(
        sa_column=Column(JSONB, default=dict),
    )

    feed_subscriptions: list["FeedSubscription"] = Relationship(
        back_populates="user",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )
    article_statuses: list["ArticleStatus"] = Relationship(
        back_populates="user",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )
    folders: list["Folder"] = Relationship(
        back_populates="user",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )
