entryPoints:
  web:
    address: ":80"

providers:
  file:
    filename: "/etc/traefik/traefik.yml"
    watch: true

http:
  routers:
    app:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      service: app

  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app:5555"

